-- MySQL Script generated by MySQL Workbench
-- 08/07/16 21:53:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lexcorp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lexcorp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lexcorp` DEFAULT CHARACTER SET utf8 ;
USE `lexcorp` ;

-- -----------------------------------------------------
-- Table `lexcorp`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lexcorp`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lexcorp`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lexcorp`.`tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `prazo` DATE NULL,
  `data_fim` DATE NULL,
  `motivo` TEXT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tarefas_estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_tarefas_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `lexcorp`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lexcorp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lexcorp`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `lexcorp`.`estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `lexcorp`;
INSERT INTO `lexcorp`.`estado` (`id`, `estado`) VALUES (1, 'Andamento');
INSERT INTO `lexcorp`.`estado` (`id`, `estado`) VALUES (2, 'Falhou');
INSERT INTO `lexcorp`.`estado` (`id`, `estado`) VALUES (3, 'Sucesso');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lexcorp`.`tarefas`
-- -----------------------------------------------------
START TRANSACTION;
USE `lexcorp`;
INSERT INTO `lexcorp`.`tarefas` (`id`, `descricao`, `data_inicio`, `prazo`, `data_fim`, `motivo`, `estado_id`) VALUES (1, 'A', '1998-11-17', '2016-11-17', '2016-11-18', 'Deu ruim', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lexcorp`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `lexcorp`;
INSERT INTO `lexcorp`.`usuario` (`id`, `usuario`, `senha`) VALUES (1, 'admin', 'admin');

COMMIT;

